export const styles = {
  container: {
    zIndex: 100,
    position: "fixed",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  modal: {
    marginTop: 20,
    borderRadius: 12,
    borderWidth: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  modalText: {
    fontSize: 20,
    textAlign: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    fontWeight: "bold",
  },
  button: {
    width: "40px",
    height: "40px",
    textAlign: "center",
    color: "white",
    border: "none",
    borderRadius: 5,
    cursor: "pointer",
    fontSize: 16,
    fontWeight: "bold",
    outline: "none",
  },
};
